function  display_struct(setup)
% >> display_struct(setup). A function which returns all the parameters 
% contained in the structure, setup, where setup is generated by the 
% script parameters. 

disp(' ')
[nr, nc] = size(setup.f);
if nr == 1 & nc == 1    
    s1= ['setup.f = '  num2str(setup.f) ];
 else
    s1 =['setup.f = ' '[' num2str(nr) 'x' num2str(nc) ' double]'];
    end
disp(s1)
s2 = [ 'setup.type1 = ' '''' setup.type1 ''''];
disp(s2)
s3 =[ 'setup.type2 = ' '''' setup.type2  ''''];
disp(s3)
s4 =['setup.int = ' '''' setup.int ''''];
disp( s4)

disp('setup.trans =')
disp(setup.trans)
disp('setup.geom =')
disp(setup.geom)
disp('setup.matl =')
disp(setup.matl)
